In [232]:
import torch

In [10]:
x = torch.ones(3, 3)
y = 2 * x
z = 3 * x
t = torch.stack([y, z], dim=2)

In [11]:
t.shape

torch.Size([3, 3, 2])

In [13]:
x.shape

torch.Size([3, 3])

In [16]:
x[:, :, None] * t

tensor([[[2., 3.],
         [2., 3.],
         [2., 3.]],

        [[2., 3.],
         [2., 3.],
         [2., 3.]],

        [[2., 3.],
         [2., 3.],
         [2., 3.]]])

In [17]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
t

tensor([[[2., 3.],
         [2., 3.],
         [2., 3.]],

        [[2., 3.],
         [2., 3.],
         [2., 3.]],

        [[2., 3.],
         [2., 3.],
         [2., 3.]]])

In [390]:
a = torch.ones(3, 1)
b = torch.ones(5) * 2
c = torch.ones(5) * 3
d = torch.stack([b, c],dim=1)
m = torch.randn(3, 5)

aa = torch.concat([a, a],dim=1)

In [303]:
a @ b[None, :]

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [304]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [305]:
e = torch.einsum('ij, jkm->mik', a, d[None, :, :])

In [306]:
e

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])

In [307]:
dd

tensor([[2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.]])

In [308]:
dd = d.T
(dd * e).shape

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

In [309]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [310]:
f = torch.einsum('ijk, ki->ji', e, d)
f

tensor([[20., 45.],
        [20., 45.],
        [20., 45.]])

In [289]:
e

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])

In [290]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [320]:
eT = e.reshape(2, 5, 3)
g = torch.einsum('ijk, ki->ji', eT, a)
g

tensor([[6., 9.],
        [6., 9.],
        [6., 9.],
        [6., 9.],
        [6., 9.]])

In [321]:
d / g

tensor([[0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333],
        [0.3333, 0.3333]])

In [324]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [329]:

res = torch.einsum('ik,kij,jk,ij->k', a, e, d, m)
res

tensor([10.8688, 24.4548])

In [330]:
a

tensor([[1.],
        [1.],
        [1.]])

In [331]:
e

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])

In [332]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [365]:
(a[None, :,:] + d.T[:,None, :])

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [340]:
a

tensor([[1.],
        [1.],
        [1.]])

In [341]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [361]:
a + d[:, 0]

tensor([[3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.],
        [3., 3., 3., 3., 3.]])

In [366]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [382]:
d[:, 0][:, None] + d[:, 0][None, :]

tensor([[4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.],
        [4., 4., 4., 4., 4.]])

In [381]:
ee = d.T[:, :, None] + d.T[:, None, :]
ee

tensor([[[4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.],
         [4., 4., 4., 4., 4.]],

        [[6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6.],
         [6., 6., 6., 6., 6.]]])

In [377]:
ee.shape

torch.Size([2, 5, 5])

In [378]:
e.shape

torch.Size([2, 3, 5])

In [379]:
a

tensor([[1.],
        [1.],
        [1.]])

In [380]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])

In [391]:
aa

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [395]:
torch.einsum('ij, jkm->mik', a, d[None, :, :])

tensor([[[2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.],
         [2., 2., 2., 2., 2.]],

        [[3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.],
         [3., 3., 3., 3., 3.]]])

In [398]:
a * d[:, 0]

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [397]:
d

tensor([[2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.],
        [2., 3.]])